name: Build e Deploy
on: 
  push:
    branches: ["master"]
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out pro repositório
        uses: actions/checkout@v3
      - name: Configura usuário/e-mail
        run: |
          git config user.name "Matheus Guissi"
          git config user.email "guissimatheus@gmail.com"
      - name: Importa chave GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Configura a versão do Node
        uses: actions/setup-node@v3
      - name: Instala dependências
        run: npm install --force
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist